name: Release Slimpogrine Starter Docker image

on:
  push:
    tags:
      - org.motorbrot.slimpogrine.launcher-**
  workflow_dispatch:

jobs:
  sling-starter-release-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Login to Docker Hub
        id: login-docker-hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU # https://github.com/docker/buildx/issues/499
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Push Docker image
        run: |
          version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          mvn --batch-mode clean install -P github -Ddocker.platforms=linux/amd64,linux/arm64 \
          -Dmaven.test.skip=true -Ddocker.skip=false -Ddocker.skip.push=false \
          -Ddocker.image.name=orx0815dockerhub/slimpogrine \
          -Ddocker.image.tag=${version} -Ddocker.image.extra.tag=latest
